baseURL = "https://www.appsyncworkshop.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "AppSync Workshop"
theme = "learn"

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Derek and Lucas"
description = "Appsync Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=true

[outputs]
home = [ "HTML", "AMP" ,"RSS", "JSON"]
page = ["HTML", "AMP"]